name: Curso Django

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:9.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: [ '5432:5432' ]
        
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
                  
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -q pipenv
          pipenv sync -d
          cp contrib/env-sample .env
               
      - name: Tests with pytest
        run: |
          pipenv run pytest
